config/routes.rb
Rails.application.routes.draw do
  devise_for :userrs

  resources :homes
  post 'add_author_book' => 'homes#add_author_book'
  root 'homes#index'
  resources :users

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :users, through: :enrollments
  has_many :enrollments
  has_many :comments, as: :commentable
end

app/models/payment_history.rb
class PaymentHistory < ActiveRecord::Base
  belongs_to :purse
end

app/models/purse.rb
class Purse < ActiveRecord::Base
  belongs_to :user
  has_one :payment_history
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :address
  has_and_belongs_to_many :events
  has_many :enrollments
  has_many :games, through: :enrollments
  has_one :purse
  has_one :payment_history, through: :purse
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :events
  accepts_nested_attributes_for :games
  accepts_nested_attributes_for :comments
end

app/models/userr.rb
class Userr < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # before_action :authenticate_userr!
  protect_from_forgery with: :exception
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_userr!, :only => [:add_author_book]
  def index
    @author = Author.all
    @comment = Comment.all
    @user = User.all
    @game = Game.all

  end
  # def new
  #   @user = User.new
  #   @event = @user.events.build
  #   @comment = @user.comments.build
  #   @game = @user.games.build
  #
  # end
  def add_author_book
    puts params
    byebug
    @author = Author.create(name: params[:author_name])
    @author.books.create(name: params[:book_name])
    #render json: 'true'
    redirect_to root_path
  end
  # def create
  #   puts params
  #   byebug
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @event = @user.events.build
    @comment = @user.comments.build
    @game = @user.games.build
    @address = @user.build_address

  end
  def create
    puts params
    byebug
    @user = User.new(user_params)
    if @user.save!
      redirect_to root_path
    else
      flash[:error] = "Can't save problems occured"
      redirect_to root_path
    end

  end
  def user_params
    params.require(:user).permit(:id,:name,address_attributes: [:city,:street,:country],events_attributes: [:title],comments_attributes: [:body],games_attributes: [:title])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="row">
  <div class= "col-md-5 col-xs-12" style="margin:20px;">
    <h1>About Books</h1>
  <table class="table table-hover table-bordered" id="table1">
    <thead class="thead-inverse">
      <tr>
        <th>Author name</th>
        <th>Books</th>
      </tr>

    </thead>
    <% @author.each do |i| %>
    <tr>
    <td><%=  i.name %></td>
    <% i.books.each do |c| %>
    <td><%= c.name%></td>
    <%end%>
    </tr>
    <%end%>
  </table>
</div>
  <div class="col-md-5 col-xs-12" style="margin:20px;">
  <h1>About comments</h1>
  <table class="table table-hover table-bordered" id="table2">
    <thead  class="thead-inverse">
      <tr>
        <th>Type</th>
        <th>Commneted_by</th>
        <th>Comment</th>
      </tr>

    </thead>

    <tbody>
      <%@comment.each do |i|%>
      <tr>
      <td>
        <%= i.commentable_type%>
      </td>

      <td>
        <%if i.commentable_type == "User"%>
        <%=User.all.where(id: i.commentable_id).first.name%>
        <%else%>
        <%= Game.all.where(id: i.commentable_id).first.title%>
        <%end%>
      </td>
      <td>
        <%= i.body%>
      </td>
      </tr>
      <%end%>
  </tbody>
  </table>
</div>
</div>
<div class="row">
  <div class="col-md-6 col-xs-12">
    <form class="form-inline" action="/add_author_book" method="post">
      <label for="author">Author Name:</label>
      <input type="text" name="author_name" value="" id="author" class="form-control">
      <label for="book">Book Name</label>
      <input type="text" name="book_name" value="" id="book" class="form-control">
      <button type="submit" name="button" id="submit" class="form-control btn btn-block-large btn-default" class="form-control">ADD</button>
    </form>
  </div>
</div>
<div class="row" style="margin:40px;">
  <table class="table table-hover table-bordered" style="text-align:center;">
    <thead style="text-align:center;">
      <tr>
        <th>
          Name
        </th>
        <th>
          Events
        </th>
        <th>
          Games
        </th>
        <th>
          Comments
        </th>
        <th>
          Enrollments
        </th>
      </tr>
    </thead>
    <tbody>
      <% @user.each do |user| %>
        <tr>
          <td>
            <%= user.name %>
          </td>
          <td>
            <ul>
              <%user.events.each do |event|%>
               <li><%=event.title%></li>
              <%end%>
            </ul>
          </td>
          <td>
            <ul>
              <%user.games.each do |game|%>
               <li><%=game.title%></li>
              <%end%>
            </ul>
          </td>
          <td>
            <ul>
              <%user.comments.each do |comment|%>
               <li><%=comment.body%></li>
              <%end%>
            </ul>
          </td>
          <td>
            <ul>
              <%user.enrollments.each do |enrollment|%>
               <li><p><%=enrollment.user.name%></p><strong>For</strong> <p><%=enrollment.game.title%></p></li>
              <%end%>
            </ul>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
<div class="row">
 <%=link_to 'Add User',new_user_path,class: "btn btn-lg btn-primary"%>  
</div>
<script type="text/javascript">
$(document).on('click','#submit',function(){
  if (!$('#author').val() || !$('#book').val()) {
    alert("please fill the required entries")
    return false;
  }
  var x = $('#author').val();
  console.log(x);
  var y = $('#book').val();
  console.log(y);
  // $.ajax({
  //   type: 'POST',
  //   url: '/add_author_book',
  //   dataType: 'json',
  //   data: {author_data: x,book_data: y},
  //   success: function(data) {
  //     console.log(data);
  //     alert("Author added");
  //     location.reload(true)
  //   }
  // });
});



</script>

app/views/homes/new.html.erb
<div class="row" style="margin:40px;">
  <h3>Form for User<h3>
    <%=form_for @user do |user|%>
      <label for="name">Name</label>
      <%=user.text_field :name, class: "form-control",placeholder: "Enter User Name", required: "required" %>
        <%=user.fields_for :events do |eve|%>
          <label for="title">Event</label>
          <%=eve.text_field :title, class: "form-control",placeholder: "Enter Event Name", required: "required" %>
        <%end%>
        <%=user.fields_for :address do |add|%>
          <label for="name">Street</label>
          <%=add.text_field :street, class: "form-control",placeholder: "Enter Street", required: "required" %>
          <label for="name">City</label>
          <%=add.text_field :city, class: "form-control",placeholder: "Enter City", required: "required" %>
          <label for="name">Country</label>
          <%=add.text_field :country, class: "form-control",placeholder: "Enter Country", required: "required" %>
        <%end%>
        <%=user.fields_for :comments do |comment|%>
          <label for="name">Comment</label>
          <%=comment.text_field :body, class: "form-control",placeholder: "Enter Comment", required: "required" %>
        <%end%>
        <%=user.fields_for :games do |game|%>
          <label for="name">Game</label>
          <%=game.text_field :title, class: "form-control",placeholder: "Enter Game", required: "required" %>
        <%end%>
      <%=user.submit "Register",style:"margin-top:20px;", data: { disable_with: "Please Wait...."}, class: "btn btn-large btn-primary", id: "user_submit"%>
    <%end%>
</div>
<h1>check for git</h1>

app/views/layouts/_header.html.erb
<div class="wrapper">
  <header class="navbar" style="background-color: aliceblue">
    <div class="navbar-brand nav">
      <%=link_to "FindShop",'#'%>
    </div>
    <nav class="primary start main-menu">
      <ul class="nav navbar-nav pull-right">
        <%if current_userr.present?%>
        <li><%=link_to "My Profile", '#'%></li>
        <%else%>
        <li><%= link_to "Login",userr_session_path%></li>
        <%end%>
        <%if current_userr.present?%>
        <li><%=link_to "logout",destroy_userr_session_path, method: :delete%></li>
        <%else%>
        <li><%=link_to "Sign Up",new_userr_registration_path%></li>
        <%end%>
        <li><%= link_to "About Us",'#'%></li>
        <li><%= link_to "Home",root_path%></li>
      </ul>
    </nav>
  </header>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExcerciseRails</title>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
</head>
<body>
<div class="wrapper">
  <%= render partial: "layouts/header"%>
</div>
<%= yield %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/userrs/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/new.html.erb
<div class="row" style="margin:40px;">
  <h3>Form for User<h3>
    <%=form_for @user do |user|%>
    <label for="name">Name</label>
    <%=user.text_field :name, class: "form-control",placeholder: "Enter User Name", required: "required" %>
    <%=user.fields_for :events do |eve|%>
    <label for="name">Event</label>
    <%=eve.text_field :title, class: "form-control",placeholder: "Enter User Name", required: "required" %>
    <%end%>
    <%=user.fields_for :address do |add|%>
    <label for="name">Street</label>
    <%=add.text_field :street, class: "form-control",placeholder: "Enter Street", required: "required" %>
    <label for="name">City</label>
    <%=add.text_field :city, class: "form-control",placeholder: "Enter City", required: "required" %>
    <label for="name">Country</label>
    <%=add.text_field :country, class: "form-control",placeholder: "Enter Country", required: "required" %>
    <%end%>
    <%=user.fields_for :comments do |comment|%>
    <label for="name">Comment</label>
    <%=comment.text_field :body, class: "form-control",placeholder: "Enter Comment", required: "required" %>
    <%end%>
    <%=user.fields_for :games do |game|%>
    <label for="name">Game</label>
    <%=game.text_field :title, class: "form-control",placeholder: "Enter Game", required: "required" %>
    <%end%>
    <%=user.submit "Register",style:"margin-top:20px;", data: { disable_with: "Please Wait...."}, class: "btn btn-large btn-primary", id: "user_submit"%>

    <%end%>
</div>